name = "jizhang-api"
main = "index.js"
compatibility_date = "2024-04-03"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "jizhang-db"
database_id = "8c583900-2d5c-4f06-9cd4-47f820fb08d7" # Replace with your actual D1 Database ID after running `npx wrangler d1 create jizhang-db`

[observability]
enabled = true
